site_name: ClamAV - Alpine Docs
theme: 
  name: readthedocs
  highlightjs: true
  include_sidebar: true
plugins:
  - search
markdown_extensions:
  - admonition

nav:
  - Home: index.md
  - Installation: #how-to
  - Usage: #usage
  - Expeted Output: #expected-output
  - Supported Tags | Versions: #supported-tags--versions
  - Changelog: #changelog
  